config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  get 'api-registration', to: 'home#register_api'

  post 'api-registration', to: 'home#store_api'

  get 'api-identification', to: 'home#identificate_api'

  post 'api-identification', to: 'home#identificate_api'

  get 'app/:app_token', to: 'home#api_dashboard', as: 'api_dashboard'

  get 'api-documentation', to: 'home#api_documentation'

  # resources :article_comments
  # resources :articles
  # resources :apis
  # resources :users

  namespace 'api' do
    get 'articles', to: 'articles#index', as: :articles

    get 'articles/:article_id/comments', to: 'articles#comments', as: :article_comments

    namespace 'users' do
      post 'identification', to: 'auth#identification'

      post 'login', to: 'auth#login'

      post 'register', to: 'auth#register'

      scope '/articles' do
        post '/create', to: 'articles#create', as: :articles_submit

        post '/like_dislike', to: 'articles#like_dislike', as: :articles_like_dislike

        post '/bookmark_un_bookmark', to: 'articles#bookmark_un_bookmark', as: :articles_bookmark_un_bookmark

        post '/comment', to: 'articles#comment', as: :articles_comments_submit
      end

      scope '/account' do
        post '/bookmarks', to: 'account#bookmarks'
      end
    end
  end
end

app/models/article_comment.rb
class ArticleComment < ApplicationRecord
  belongs_to :article, counter_cache: 'comments_count'
  belongs_to :api, counter_cache: 'articles_comments_count'
  belongs_to :user

  def created_at_timestamp
    created_at.to_i * 1000
  end
end

app/controllers/admin/article_comments_controller.rb
class ArticleCommentsController < ApplicationController
  before_action :set_article_comment, only: [:show, :edit, :update, :destroy]

  # GET /article_comments
  # GET /article_comments.json
  def index
    @article_comments = ArticleComment.all
  end

  # GET /article_comments/1
  # GET /article_comments/1.json
  def show
  end

  # GET /article_comments/new
  def new
    @article_comment = ArticleComment.new
  end

  # GET /article_comments/1/edit
  def edit
  end

  # POST /article_comments
  # POST /article_comments.json
  def create
    @article_comment = ArticleComment.new(article_comment_params)

    respond_to do |format|
      if @article_comment.save
        format.html { redirect_to @article_comment, notice: 'Article comment was successfully created.' }
        format.json { render :show, status: :created, location: @article_comment }
      else
        format.html { render :new }
        format.json { render json: @article_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /article_comments/1
  # PATCH/PUT /article_comments/1.json
  def update
    respond_to do |format|
      if @article_comment.update(article_comment_params)
        format.html { redirect_to @article_comment, notice: 'Article comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @article_comment }
      else
        format.html { render :edit }
        format.json { render json: @article_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /article_comments/1
  # DELETE /article_comments/1.json
  def destroy
    @article_comment.destroy
    respond_to do |format|
      format.html { redirect_to article_comments_url, notice: 'Article comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article_comment
      @article_comment = ArticleComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_comment_params
      params.require(:article_comment).permit(:content)
    end
end

app/helpers/article_comments_helper.rb
module ArticleCommentsHelper
end

app/views/admin/article_comments/_form.html.erb
<%= form_with(model: article_comment, local: true) do |form| %>
  <% if article_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article_comment.errors.count, "error") %> prohibited this article_comment from being saved:</h2>

      <ul>
      <% article_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/article_comments/edit.html.erb
<h1>Editing Article Comment</h1>

<%= render 'form', article_comment: @article_comment %>

<%= link_to 'Show', @article_comment %> |
<%= link_to 'Back', article_comments_path %>

app/views/admin/article_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Article Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @article_comments.each do |article_comment| %>
      <tr>
        <td><%= article_comment.content %></td>
        <td><%= link_to 'Show', article_comment %></td>
        <td><%= link_to 'Edit', edit_article_comment_path(article_comment) %></td>
        <td><%= link_to 'Destroy', article_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article Comment', new_article_comment_path %>

app/views/admin/article_comments/new.html.erb
<h1>New Article Comment</h1>

<%= render 'form', article_comment: @article_comment %>

<%= link_to 'Back', article_comments_path %>

app/views/admin/article_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @article_comment.content %>
</p>

<%= link_to 'Edit', edit_article_comment_path(@article_comment) %> |
<%= link_to 'Back', article_comments_path %>