config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  get 'api-registration', to: 'home#register_api'

  post 'api-registration', to: 'home#store_api'

  get 'api-identification', to: 'home#identificate_api'

  post 'api-identification', to: 'home#identificate_api'

  get 'app/:app_token', to: 'home#api_dashboard', as: 'api_dashboard'

  get 'api-documentation', to: 'home#api_documentation'

  # resources :article_comments
  # resources :articles
  # resources :apis
  # resources :users

  namespace 'api' do
    get 'articles', to: 'articles#index', as: :articles

    get 'articles/:article_id/comments', to: 'articles#comments', as: :article_comments

    namespace 'users' do
      post 'identification', to: 'auth#identification'

      post 'login', to: 'auth#login'

      post 'register', to: 'auth#register'

      scope '/articles' do
        post '/create', to: 'articles#create', as: :articles_submit

        post '/like_dislike', to: 'articles#like_dislike', as: :articles_like_dislike

        post '/bookmark_un_bookmark', to: 'articles#bookmark_un_bookmark', as: :articles_bookmark_un_bookmark

        post '/comment', to: 'articles#comment', as: :articles_comments_submit
      end

      scope '/account' do
        post '/bookmarks', to: 'account#bookmarks'
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def register_api
    @api = Api.new
  end

  def store_api
    @api = Api.new(api_params)
    @api.app_token = SecureRandom.uuid

    if @api.save
      return redirect_to api_dashboard_url(app_token: @api)
    end

    render 'home/register_api'
  end

  def identificate_api
    params.permit(:email, :password)

    unless params[:email].nil? and params[:password].nil?
      @api = Api.find_by_email params[:email]

      unless @api.nil?
        return redirect_to api_dashboard_url(app_token: @api) if @api.authenticate(params[:password])
      end

      @message = "These credentials don't match our records."
    end
  end

  def api_dashboard
    @api = Api.find_by_app_token params[:app_token]

    return render_404 if @api.nil?

    @api_last_user = User.order(created_at: :desc).where(api_id: @api.id).select(:created_at).first
    @api_last_article = Article.order(created_at: :desc).where(api_id: @api.id).select(:created_at).first
    @api_last_article_comment = ArticleComment.order(created_at: :desc).where(api_id: @api.id).select(:created_at).first
    @api_last_article_like = ArticleLike.order(created_at: :desc).where(api_id: @api.id).select(:created_at).first
    @api_last_user_bookmark = UserBookmark.order(created_at: :desc).where(api_id: @api.id).select(:created_at).first
  end

  def api_documentation

  end

  private

  def api_params
    params.require(:api).permit(:full_name, :app_name, :app_description, :email, :password, :password_confirmation)
  end
end

app/views/home/_footer.html.erb
<br>

<hr class="my-4">
<p class="text-center">Design by <a href="https://gitlab.com/longbowou" target="_blank">Longbowou</a> © Copyright
  2019.</p>
<br>
<br>
<br>

app/views/home/_form.html.erb
<%= form_for @api, url: api_registration_path, html: {} do |form| %>
  <% if @api.errors.any? %>
    <% @api.errors.full_messages.each do |message| %>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong><%= message %></strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= form.label :app_name, "Your app name" %>
    <%= form.text_field :app_name, class: (@api.errors[:app_name].any? ? "form-control is-invalid" : "form-control"), placeholder: 'App name', required: '' %>
  </div>

  <div class="form-group">
    <%= form.label :app_description, "Your app description" %>
    <%= form.text_area :app_description, class: (@api.errors[:app_description].any? ? "form-control is-invalid" : "form-control"), placeholder: 'App description', required: '', rows: 5 %>
  </div>

  <div class="form-group">
    <%= form.label :full_name %>
    <%= form.text_field :full_name, class: (@api.errors[:full_name].any? ? "form-control is-invalid" : "form-control"), placeholder: 'Full name', required: '' %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: (@api.errors[:email].any? ? "form-control is-invalid" : "form-control"), placeholder: 'Email', required: '' %>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: (@api.errors[:password].any? ? "form-control is-invalid" : "form-control"), placeholder: 'Password', required: '' %>
  </div>

  <div class="form-group">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: (@api.errors[:password_confirmation].any? ? "form-control is-invalid" : "form-control"), placeholder: 'Password confirmation', required: '' %>
  </div>

  <button type="submit" class="btn btn-secondary">Submit</button>
<% end %>

app/views/home/api_dashboard.html.erb
<% content_for :title do %>
  App dashboard
<% end %>

<div class="container">
  <br>
  <br>
  <br>

  <h2 class="text-center">👋 Welcome <%= @api.full_name %> to
    <strong><a href="<%= root_path %>">Dummy Api</a></strong>.</h2>
  <h4 class="text-center">Check bellow you app information.</h4>
  <h6 class="text-center">Check also <strong><a href="<%= root_path %>">Dummy Api</a></strong>
    <a href="<%= api_documentation_path %>">documentation</a>.</h6>
  <hr class="my-4">

  <br>

  <div class="row justify-content-sm-center">
    <div class="col-sm-6">
      <h3 class="text-center">Your app information</h3>
      <label>App name:</label>
      <p><strong><%= @api.app_name %></strong></p>

      <br>

      <label>App description:</label>
      <p><strong><%= @api.app_description %></strong></p>

      <br>

      <label>App token:</label>
      <p id="app-token"><strong><%= @api.app_token %></strong></p>
    </div>
  </div>

  <hr class="my-4">
  <br>

  <h3 class="text-center">Your app statistics</h3>
  <br>

  <div class="row justify-content-sm-center">
    <div class="col-sm-4">
      <div class="card text-center">
        <div class="card-body">
          <h5 class="card-title">Users</h5>
          <h1 class="card-text"><%= @api.users_count %></h1>
          <p class="card-text">
            <% unless @api_last_user.nil? %>
              <small class="text-muted">Last user
                register <%= distance_of_time_in_words_to_now @api_last_user.created_at %> ago
              </small>
            <% end %>
          </p>
        </div>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="card text-center">
        <div class="card-body">
          <h5 class="card-title">Articles</h5>
          <h1 class="card-text"><%= @api.articles_count %></h1>
          <p class="card-text">
            <% unless @api_last_article.nil? %>
              <small class="text-muted">Last article
                created <%= distance_of_time_in_words_to_now @api_last_article.created_at %> ago
              </small>
            <% end %>
          </p>
        </div>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="card text-center">
        <div class="card-body">
          <h5 class="card-title">Comments</h5>
          <h1 class="card-text"><%= @api.articles_comments_count %></h1>
          <p class="card-text">
            <% unless @api_last_article_comment.nil? %>
              <small class="text-muted">Last comment
                created <%= distance_of_time_in_words_to_now @api_last_article_comment.created_at %> ago
              </small>
            <% end %>

          </p>
        </div>
      </div>
    </div>

    <div class="col-sm-4" style="margin-top: 20px">
      <div class="card text-center">
        <div class="card-body">
          <h5 class="card-title">Bookmarks</h5>
          <h1 class="card-text"><%= @api.users_bookmarks_count %></h1>
          <p class="card-text">
            <% unless @api_last_user_bookmark.nil? %>
              <small class="text-muted">Last bookmark
                created <%= distance_of_time_in_words_to_now @api_last_user_bookmark.created_at %> ago
              </small>
            <% end %>
          </p>
        </div>
      </div>
    </div>

    <div class="col-sm-4" style="margin-top: 20px">
      <div class="card text-center">
        <div class="card-body">
          <h5 class="card-title">Likes</h5>
          <h1 class="card-text"><%= @api.articles_likes_count %></h1>
          <p class="card-text">
            <% unless @api_last_article_like.nil? %>
              <small class="text-muted">Last like
                created <%= distance_of_time_in_words_to_now @api_last_article_like.created_at %> ago
              </small>
            <% end %>
          </p>
        </div>
      </div>
    </div>

  </div>

  <%= render 'home/footer' %>
</div>

<% content_for :stylesheet do %>
  <script type="text/javascript" charset="utf-8">

      function onClick() {
          // document.querySelector('#app-token').style.color = '#e83e8c'
      }
  </script>
<% end %>

app/views/home/identificate_api.html.erb
<% content_for :title do %>
  Api identification
<% end %>

<div class="container">
  <br>
  <br>

  <div class="row justify-content-sm-center">
    <div class="col-sm-12 col-md-10 col-lg-8">
      <h2 class="text-center">👋 Welcome back to
        <strong><a href="<%= root_path %>">Dummy Api</a></strong>.</h2>
      <h4 class="text-center">Please fill the form bellow to get identify.</h4>
      <h6 class="text-center">I don't have an <a href="<%= api_registration_path %>">access token</a>.</h6>
      <h6 class="text-center">Check also <strong><a href="<%= root_path %>">Dummy Api</a></strong>
        <a href="<%= api_documentation_path %>">documentation</a>.</h6>
      <hr class="my-4">
    </div>
  </div>

  <br>

  <div class="row justify-content-sm-center">
    <div class="col-sm-12 col-md-10 col-lg-8">
      <% unless @message.nil? %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <strong><%= @message %></strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>

      <%= form_tag(api_identification_path, method: :post) do %>
        <div class="form-group">
          <label for="exampleInputEmail1">Email</label>
          <input name="email" type="email" class="form-control" id="exampleInputEmail1" placeholder="Email" value="<%= params[:email] %>" required>
        </div>

        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          <input name="password" type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" required>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
      <% end %>
    </div>
  </div>

  <%= render 'home/footer' %>
</div>

app/views/home/index.html.erb
<% content_for :title do %>
  Welcome
<% end %>

<div class="container">
  <br>
  <br>

  <div class="row justify-content-center">
    <div class="col-sm-12 col-md-10-col-lg-8">
      <div class="jumbotron">
        <h1 class="display-4 text-center">Rails Dummy Api 😺</h1>
        <div class="lead">
          <p class="text-center">
            Welcome 👋. This is the <a href="https://rubyonrails.org/" target="_blank">Rails</a> version of
            <strong>Dummy Api</strong>. <strong>Dummy Api</strong> is a simple basic
            <a href="https://en.wikipedia.org/wiki/Application_programming_interface" target="_blank">api</a> with dummy
            content.
          </p>
          <hr class="my-4">
          <p>It
            offer basic features like :</p>
          <ul>
            <li>User authentication with phone number</li>
            <li>Create articles</li>
            <li>Comment articles</li>
            <li>Bookmark articles</li>
          </ul>
        </div>
        <p class="">Are you interested ? You are welcome. Take a look at <a href="#step-one">steps</a>
          bellow to get ready using <strong>Dummy Api</strong>.</p>
        <p class="text-center">Enjoy it. We are <strong>dummy</strong>. 🤙</p>
        <hr class="my-4">
        <p>Thanks 🙏 to contributors on our
          <a href="https://gitlab.com/longbowou/dummy-rails" target="_blank">gitlab repository</a>:
        </p>
        <ul>
          <li><a href="https://gitlab.com/longbowou" target="_blank">Longbowou</a></li>
        </ul>
        <hr class="my-4">
        <p>Check this <a href="https://gitlab.com/longbowou/dummy-android-java" target="_blank">android</a>
          implementation
          of <strong>Dummy Api</strong>. We hope you appreciate. Contributors a also welcome. </p>
      </div>
    </div>
  </div>

  <br>

  <div class="row justify-content-center">
    <div class="col-sm-12 col-md-10-col-lg-8">
      <h2>Get started</h2>
      <p>
        <strong>Dummy Api</strong> provide api that is protected by an access token. To access and use
        <strong>Dummy Api</strong> you must
        <a href="<%= api_registration_path %>">register</a> and to get an access token.
      </p>

      <br>

      <h4 id="step-one">1 - Register your app to get an access token</h4>
      <p>go to this <a href="<%= api_registration_path %>">url</a> and fill the form to get your access token.</p>

      <br>
      <br>

      <h4>2 - Read api documentation</h4>
      <p>This is where you can find technical <a href="<%= api_documentation_path %>">documentation</a> about api.</p>

      <br>
      <br>

      <h4>3 - Enjoy and share</h4>
      <p>😺 Enjoy <strong>Dummy Api</strong> ! Please <a href="#">share with us</a> what you have built with
        <strong>Dummy Api</strong>.</p>

      <hr class="my-4">
      <div class="row justify-content-sm-center">
        <div class="col-sm-4">
          <div class="form-group">
            <label for="email">Subscribe to our newsletters</label>
            <input type="email" class="form-control" placeholder="exemble@yahoo.fr">
          </div>

          <button type="button" class="btn btn-secondary">Subscribe</button>

        </div>
      </div>
    </div>
  </div>

  <%= render 'home/footer' %>
</div>

app/views/home/register_api.html.erb
<% content_for :title do %>
  Api registration
<% end %>

<div class="container">
  <br>
  <br>

  <div class="row justify-content-sm-center">
    <div class="col-sm-12 col-md-10 col-lg-8">
      <h2 class="text-center">👋 Here is where you can get an access token to use
        <strong><a href="<%= root_path %>">Dummy Api</a></strong>.</h2>
      <h4 class="text-center">Please fill the form bellow.</h4>
      <h6 class="text-center">I already get my <a href="<%= api_identification_path %>">access token</a>.</h6>
      <h6 class="text-center">Check also <strong><a href="<%= root_path %>">Dummy Api</a></strong>
        <a href="<%= api_documentation_path %>">documentation</a>.</h6>
      <hr class="my-4">
    </div>
  </div>

  <br>

  <div class="row justify-content-sm-center">
    <div class="col-sm-12 col-md-10 col-lg-8">
      <%= render 'home/form' %>
    </div>
  </div>

  <%= render 'home/footer' %>
</div>